import ibm_db 
import pathlib

db = ibm_db.connect("DATABASE=bludb;QUERYTIMEOUT=1;CONNECTTIMEOUT=10;HOSTNAME=55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud;PORT=31929;SECURITY=SSL;SSLServerCertificate={};PROTOCOL=TCPIP;UID=qkv66262;PWD=AdYZNvQ1IXXgHuaX".format(str(pathlib.Path(__file__).parent.resolve())+"/DigiCertGlobalRootCA.crt"), "", "")


defined_sql_statements = ["CREATE TABLE USERS(ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), NAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL UNIQUE, PASSWORD VARCHAR(255) NOT NULL, CURRENCY VARCHAR(3) NOT NULL, TOKEN VARCHAR(255) NOT NULL, VERIFIED BOOLEAN DEFAULT FALSE)", "CREATE TABLE CATEGORY(ID INT NOT NULL, NAME VARCHAR(255), KEY VARCHAR(255))","CREATE TABLE TRANSACTIONS(ID INT PRIMARY KEY NOT NULL, AMOUNT VARCHAR(50) NOT NULL, DATE DATE NOT NULL, CATEGORY VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255), TYPE VARCHAR(1) NOT NULL, USER INT NOT NULL FOREIGN_KEY REFERENCES USERS)", "CREATE TABLE BUDGETS(NAME VARCHAR(60) NOT NULL, CREATED_AT DATE NOT NULL, RANGE VARCHAR(1) NOT NULL, LIMIT VARCHAR(60) NOT NULL, USER INT FOREIGN_KEY REFERENCES USERS)"]

for query in defined_sql_statements:
    ibm_db.exec_immediate(db, query)



